name: Ejecucion y Guardado Automatico Futbol 2026

on:
  schedule:
    - cron: '0 23 * * 0,3'
    - cron: '0 17 * * 2,5'
  workflow_dispatch:

jobs:
  ejecutar:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v3

      - name: Instalar Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Instalar librerias
        run: |
          pip install pandas numpy requests

      - name: Ejecutar sistema de analisis
        run: python main.py

      - name: Guardar cambios
        run: |
          git config --global user.name "futbol-bot"
          git config --global user.email "bot@github.com"
          git add .
          git commit -m "Actualizacion automatica sistema futbol 2026" || echo "Sin cambios"
          git push
